# config/config.yaml
app:
  name: Powerbase Test Client
  env: dev
server:
  host: 127.0.0.1
  port: 9000
features:
  - orders
  - executions
  - monitor

host: 127.0.0.1
port: 5000

# framing:
#  - ascii  : 4 ASCII bytes like "0123"
#  - binary : 4-byte unsigned int
framing: binary
endian: BE                  # BE or LE (only for binary framing)
length_includes_header: true

charset: EUC-KR             # or UTF-8
normalize: true             # NFC normalization

log_recv_hex: true
log_send_hex: true
